Реализация event repository
craftyard/backend-core pull request #9
Opened 2024-01-10 09:40 UTC by ThiagoRouge

2024-01-10 11:49 UTC, xHetso approved these changes

2024-01-11 03:13 UTC, NurGeo requested changes
Хорошая работа, я не шучу. Не смотри что "много" комментариев.
Не ставлю approve, потому что требуемые изменения критичны, касаются изменений интерфейса.

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.test.ts
> +  await typeormDatabase.init();
а действительно ли надо для каждого теста делать init()?

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.test.ts
> +    expect(eventEntity.attrs).toBe('{"attrs":{"username":"azat","age":19},"meta":{"eventId":"d00103e8-eb18-4694-9efd-ce0b2dcbf0d7","actionId":"c7ab5938-ac52-47d6-b831-62fbd3cbc288","name":"nameeee","
1. почему имя евента такое странное и неговорящее?
2. `aRootAttrs":{"attrs":{}...` объект aRootAttrs должен содержать последнее состояние агрегата, в твоем случае его состояние пустое.
3. Почему `aRootAttrs.meta.name` пустое?

Понимаю, это не повлияет на сам тест, но повторяю, через тесты мы рассказываем как устроена наша архитектура, и твой тест говорит будущему читателю, что в этом поле может быть пустой объект.

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.test.ts
> +        name: 'kakoitoname',
как ты думаешь, это name чего?

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.test.ts
> +          name: '',
??

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/entities/event.ts
> +    actionId!: string;
добавь комментарий jsDoc который скажет что primaryKey ставится actionDod, потому что есть вероятность что мы будем проверять перед работой service обрабатывался ли уже данный actionDod?

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/entities/event.ts
> +
Нужен новое поле. aRootId:
type: UuidType, unique: false,

Для чего? Если нам понадобится прочитать все события определенного агрегата.
Определи в интерфейсе репозитория соответствующий метод, потом реализуй ее. Обязательно предварительно согласовать изменения в интерфейсе.

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.test.ts
> +        age: 19,
сделай другого человека, чего это два события с одними данными?
И самое паршивое, смотря твой тест я даже не пойму что это за событие. Какое то событие произошло, а какое не понятно.

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.test.ts
> +  test('fail, not published events not found', async () => {
может чтобы протестировать что он не выдает не опубликованные надо добавить в БД данные? Как ты можешь быть уверен в корректной проверке, если БД пустая?

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/entities/event.ts
> +    actionId!: string;
надо добавить новый метод в интерфейс getEvent. Потом реализовать.

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.test.ts
> +  test('success, event entity marked as published', async () => {
вынеси этот тест выше, сделай ее вторым. Просто в тесте где ты тестируешь getPublished ты уже используешь этот метод, а с ним читатель твоих тестов еще не ознакомился.

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.test.ts
> +    await eventRepo.addEvent(eventDOD);
сделать проверку перед изменением статуса, что она помечена как не опубликованная.

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.ts
> +    this.entityManager = typeormDatabase.createEntityManager();
уверен что нормальная практика для ВСЕХ запросов использовать один entityManager?
Не нужно ли их создавать каждый раз? Если уверен что это норм, то дай ссылку на инфу где про это сказано.

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.ts
> +      throw await this.logger.error('db server error', e);
лучше что то вроде  "db server error by event repository"

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.ts
> +      throw await this.logger.error('db server error', e);
или "db server error: fail to save eventEntity by event repository"

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.ts
> +      throw await this.logger.error('db server error', e);
в логгер вторым параметром мы передаем данные контекста, лучше передай eventEntity, согласно нового таска, третьим параметром мы возможно передадим объект ошибки.

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/event-repo.ts
> +  async getNotPublishedEvents(): Promise<GeneralEventDod[]> {
знаешь что, а ведь этот метод будет использоваться для того чтобы опубликовать данные. А чтобы опубликовать, он его отправит по сети, а для этого он опять переведет в json. Поэтому измени интерфейс чтобы возвращал массив строк и возвращай несериализованные строки.

2024-01-11 03:13 UTC, NurGeo commented on src/infra/event-repo/fixture.ts
> +  database: 'main.sqlite',
зачем сохранять? Почему не ":memory:"?

2024-01-11 05:01 UTC, ThiagoRouge commented on src/infra/event-repo/event-repo.test.ts
> +  await typeormDatabase.init();
before All перед всеми тестами один раз

2024-01-12 07:09 UTC, ThiagoRouge commented on src/infra/event-repo/event-repo.ts
> +    this.entityManager = typeormDatabase.createEntityManager();
а смысл каждый раз создавать

2024-01-12 12:08 UTC, xHetso approved these changes

2024-01-14 17:25 UTC, yaksh0nti approved these changes

2024-01-14 17:25 UTC, yaksh0nti commented on src/infra/event-repo/event-repo.ts
> +      .map((eventEnt) => eventEnt.attrs);
а что если будешь возвращать сразу массив объектов?

2024-01-14 17:25 UTC, yaksh0nti commented on src/infra/event-repo/event-repo.ts
> +      throw await this.logger.error('db server error by event repository', eventEntity);
рекомендую написать внятные описание ошибки примеру тут 'ошибка при добавлений события')

и так везде где кидаешь ошибки а то у всех одинаковый описание а тут хотя бы сразу будет видно в каком случае вызвался ошибка)

2024-01-14 20:45 UTC, ThiagoRouge commented on src/infra/event-repo/event-repo.ts
> +      .map((eventEnt) => eventEnt.attrs);
это нужно тому, кто будет передавать эти события в шину, что бы заново не делать их строкой

2024-01-14 20:46 UTC, ThiagoRouge commented on src/infra/event-repo/event-repo.ts
> +      throw await this.logger.error('db server error by event repository', eventEntity);
нурболат сказал лучше так

2024-01-15 20:56 UTC, NurGeo approved these changes
После можешь пушить.

2024-01-15 20:56 UTC, NurGeo commented on src/infra/event-repo/event-repo.test.ts
> +    test('success, event entity added to the repo', async () => {
0орошо бы тестовый случай, что если записать евент с таким же ид, то он не запишется.

2024-01-15 20:56 UTC, NurGeo commented on src/infra/event-repo/event-repo.ts
> +    const { unitOfWorkId } = storeDispatcher.getThreadStore().getStore();
Нету проверки насчёт uowId === undefined. Если это так, то должно кидаться исключение. Проверить тестом.

2024-01-15 20:56 UTC, NurGeo commented on src/infra/event-repo/event-repo.ts
> +      throw await this.logger.error('db server error by event repository', eventEntity);
Если Нурадиль даст какое описание он хочет видеть, то можно и его написать. Я по крайней мере указал что ошибка произошла в eventRepo

2024-01-15 20:56 UTC, NurGeo commented on src/infra/event-repo/event-repo.ts
> +    if (await this.typeormDatabase.createEntityManager().existsBy(Event, { actionId })) return true;
Как будто existBy сам возвращает булевый ответ. Тогда зачем if?

2024-01-15 20:56 UTC, NurGeo commented on src/infra/event-repo/event-repo.ts
> +  async markAsPublished(eventId: string): Promise<void> {
Переименовать параметр на actionId

2024-01-23 08:05 UTC, merged